"use client";

import { useState, useEffect } from "react";
import { generateVideoSummary } from "@/app/actions";
import { Sparkles, Loader2, BrainCircuit } from "lucide-react";

interface VideoSummaryProps {
  playbackId: string;
}

export default function VideoSummary({ playbackId }: VideoSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const result = await generateVideoSummary(playbackId);
      if (result.error) {
        setError(result.error);
      } else if (result.summary) {
        setSummary(result.summary);
      }
    } catch {
      setError("An unexpected error occurred.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <section
      className="glass rounded-3xl p-6 lg:p-8 space-y-6 relative overflow-hidden group"
      aria-labelledby="ai-summary-heading"
    >
      {/* Decorative icon */}
      <div
        className="absolute top-0 right-0 p-8 opacity-8 group-hover:opacity-16 transition-opacity duration-500"
        aria-hidden="true"
      >
        <BrainCircuit className="w-24 h-24 text-primary" />
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 relative">
        <div className="flex items-center gap-2">
          <Sparkles
            className="w-5 h-5 text-primary flex-shrink-0"
            aria-hidden="true"
          />
          <h2
            id="ai-summary-heading"
            className="text-xl font-bold gradient-text-primary"
          >
            AI Video Summary
          </h2>
        </div>

        {!summary && !isLoading && (
          <button
            onClick={handleGenerate}
            className="btn btn-primary rounded-xl shadow-lg shadow-primary/20"
            aria-label="Generate AI summary for this video"
          >
            Generate with AI
          </button>
        )}
      </div>

      <div
        className="relative min-h-[100px] flex items-center justify-center"
        aria-live="polite"
        role="status"
      >
        {isLoading ? (
          <div className="flex flex-col items-center gap-4 py-8" aria-busy="true">
            <Loader2
              className="w-8 h-8 text-primary animate-spin"
              aria-hidden="true"
            />
            <p className="text-sm text-muted-foreground font-medium animate-pulse">
              Screeder AI is analyzing the transcript…
            </p>
          </div>
        ) : summary ? (
          <div className="space-y-4 w-full animate-fade-in-up">
            <p className="text-foreground leading-relaxed italic">
              &ldquo;{summary}&rdquo;
            </p>
            <div className="flex items-center gap-2">
              <div className="h-px flex-1 bg-border" />
              <span className="text-[10px] text-muted-foreground uppercase tracking-widest font-bold whitespace-nowrap">
                Generated by Screeder AI
              </span>
              <div className="h-px flex-1 bg-border" />
            </div>
          </div>
        ) : error ? (
          <div
            role="alert"
            className="p-4 bg-red-500/10 backdrop-blur-md border border-red-500/20 rounded-xl text-red-400 text-sm w-full"
          >
            {error}
          </div>
        ) : (
          <div className="py-8 text-center w-full">
            <p className="text-muted-foreground text-sm">
              Click the button above to generate a concise AI summary of this
              recording.
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
